name: async-iterable testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  quality:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x]
        os: [ubuntu-latest, windows-latest, macos-12]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: "@ruffiano"
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test